# ENV FILE FOR THE GITHUB ACTION RUNNING POSTGRESQL
APP_NAME=OfficeLife
APP_ENV=testing
APP_KEY=base64:1zIqSKT/IRwsdzeakTeYfC/In+k0BxaCtfnzw9ApxnA=
APP_DEBUG=true
APP_URL=http://localhost

DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=officelife
DB_USERNAME=officelife
DB_PASSWORD=secret

BROADCAST_CONNECTION=log
CACHE_STORE=array
FILESYSTEM_DISK=local
MAIL_MAILER=array
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
